version: 2.1

orbs:
  maven: circleci/maven@1.4.1  # Use the Maven orb
  
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - maven/with_cache:  # Use the Maven orb to handle caching and dependencies
          steps:
            - run:
                name: Build and Test
                command: mvn verify
            - run:
                name: Generate Surefire Report
                command: mvn surefire-report:report  # Generate the test report
      - store_test_results:
          path: target/surefire-reports  # Store test results
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1
            mkdir /tmp/artifacts
            echo "my artifact files in a dir" > /tmp/artifacts/art-2
      - store_artifacts: 
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
          
workflows:
  build-and-test:
    jobs:
      - test-java
