version: 2.1

orbs:
  maven: circleci/maven@3.0.0  # Use the Maven orb for simplifying Maven tasks


jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0  # Use OpenJDK 17 image (adjust if you use another version)
    steps:
      - checkout  # Check out your project
      - maven/with_cache:  # Use Maven's caching mechanism to speed up builds
          steps:
            - run:
                name: Build and Test
                command: mvn clean install  # Build and run tests
      - store_test_results:
          path: target/surefire-reports  # Store test results (Surefire plugin results)
      - store_artifacts:
          path: target  # Store the built artifacts (e.g., .jar, .war files)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
